version: 2.1
 
orbs:
  docker: circleci/docker@2.0.1
 
jobs:
  build-and-push:
    docker:
      - image: cimg/openjdk:11.0.13
    steps:
      - run:
          name: run build
          command: |
            whoami
            pwd
            echo "build success"
  deploy:
    executor: docker/docker
    steps:
      - run:
          name: run build
          command: |
            whoami
            pwd
            echo "deploy succes"
 
workflows:
  my-workflow:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - dev
      - deploy:
          requires:
            - build-and-push
          filters:
            branches:
              only:
                - master